export const data = [
  {
    id: 1,
    type: 1,
    category: "Tech",
    startDateTime: "2023-09-12T18:00:00Z",
    duration: "60",
    title: "Tech Seminar",
    meta1: "Location: Virtual",
    meta2: "Speaker: Jane Doe",
  },
  {
    id: 2,
    type: 1,
    category: "Tech",
    startDateTime: "2023-09-12T22:00:00Z",
    duration: "60",
    title: "Tech Seminar",
    meta1: "Location: Virtual",
    meta2: "Speaker: Jane Doe",
  },
  {
    id: 3,
    type: 2,
    category: "Design",
    startDateTime: "2023-09-15T19:45:00Z",
    duration: "250",
    title: "Design Discussion",
    meta1: "Location: Studio Y",
    meta2: "Instructor: John Smith",
  },
  {
    id: 4,
    type: 4,
    category: "Design",
    startDateTime: "2023-09-15T19:45:00Z",
    duration: "60",
    title: "Design Discussion",
    meta1: "Location: Studio Y",
    meta2: "Instructor: John Smith",
  },
  {
    id: 5,
    type: 3,
    category: "Design",
    startDateTime: "2023-09-15T12:15:00Z",
    duration: " .05 ",
    title: "Design Workshop",
    meta1: "Location: Studio X",
    meta2: "Instructor: Jane Smith",
  },
  {
    id: 6,
    type: 1,
    category: "dev",
    startDateTime: "2023-09-15T12:20:00Z",
    duration: "120",
    title: " Workshop",
    meta1: "Location: Studio X",
    meta2: "Instructor: Jane Smith",
  },
  {
    id: 7,
    type: 2,
    category: "Tech",
    startDateTime: "2023-09-12T12:00:00Z",
    duration: "45",
    title: "Tech Conference",
    meta1: "Location: Virtual",
    meta2: "Speaker: John Doe",
  },
  {
    id: 8,
    type: 3,
    category: "Tech",
    startDateTime: "2023-09-12T14:00:00Z",
    duration: "20",
    title: "Client meeting ",
    meta1: "Location: Virtual",
    meta2: "Speaker: John Doe",
  },
  {
    id: 9,
    type: 1,
    category: "Design",
    startDateTime: "2023-09-15T08:15:00Z",
    duration: "30",
    title: "Design Workshop",
    meta1: "Location: Studio X",
    meta2: "Instructor: Jane Smith",
  },
];
